### ISSUE TITLE
Suitecrm: E-mail addresses aren't deleted when users are

### ISSUE THREAD

**Issue by jonathanmaw** [CodethinkLabs/lifecycle#58]
The SuiteCRM data model is:
* The EmailAddress module keeps a list of E-mail addresses.
* The User module keeps a list of Users.
* The User has "relationships", including one with E-mail addresses.
  - if you query `/Api/V8/User/<id>/relationships/email_addresses`, you get the list of E-mail addresses associated with that User.

When you delete a User, that E-mail address doesn't go away.

Querying the list of E-mail addresses doesn't provide any information about whether those E-mail addresses are in any relationships, which makes it hard to see if an E-mail address is orphaned, however.

This means there's the potential that the suitecrm database will hold a lot of orphaned E-mail addresses.

If this is a problem we want to solve, we'll have to find out how to find out everywhere that an E-mail address is used, so we can delete it if it's orphaned.

**Comment by adam1noor** [comment]
This isn't currently solvable as far as I can tell so I'm going to close it for now.
